language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
os:
  - linux

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get install build-essential git libboost-all-dev cmake libgmp3-dev libssl-dev libprocps3-dev pkg-config gcc-5 g++-5

before_script:
  - git submodule init && git submodule update
  - mkdir build && cd build && cmake ..

script:
  - make
  - make check

notifications:
  email: false