language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5

before_install:
  - sudo apt-get install build-essential git libboost-all-dev cmake libgmp3-dev libssl-dev libprocps3-dev pkg-config

before_script:
  - git submodule init && git submodule update
  - mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..

script:
  - make
  - make check

notifications:
  email: false