name: main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: python_setup
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: before_install
      run: |
        sudo apt-get install build-essential git libboost-all-dev cmake libgmp3-dev libssl-dev libsodium-dev libprocps-dev pkg-config gcc-10 g++-10
        sudo apt-get install clang-tidy
        git submodule init && git submodule update
        mkdir build
        cd build
        PATH=$PATH:${PWD}
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
    - name: tests
      run: |
        cd build
        make
        make check